name: Build and Deploy Container Image to Azure App Service

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
          
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash    
      
      - name: Build
        run: |
          cd src
          go build -v ./...
      
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - uses: azure/docker-login@v1
        with:
          login-server: weatherapps.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    
      - run: |
         docker build -t weatherapps.azurecr.io/go-weather-app:${{ github.sha }} src
         docker push weatherapps.azurecr.io/go-weather-app:${{ github.sha }}
         docker tag weatherapps.azurecr.io/go-weather-app:${{ github.sha }} weatherapps.azurecr.io/go-weather-app:latest
         docker push weatherapps.azurecr.io/go-weather-app:latest     
      
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'sachinparihar'
          publish-profile: ${{ secrets.APP_SERVICE_PUBLISH_PROFILE }}
          images: 'weatherapps.azurecr.io/go-weather-app:${{ github.sha }}'
    
      - name: Azure logout
        run: |
          az logout
