name: Build Linux Container Image and Push to ACR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      
      - name: Build
        run: |
          cd go-weather-app/src
          go build -v ./...
      
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: weatherapps.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build . -t weatherapps.azurecr.io/go-weather-app:${{ github.sha }}
          docker push weatherapps.azurecr.io/go-weather-app:${{ github.sha }}
