name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Build
      run: |
        cd src/Backend
        go build -buildmode=exe -o weather-app ./main.go

    - name: Test
      run: |
        cd src/Backend
        go test ./...

    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & push Docker image
      with:
        image: sachinparihar/go-weather-apps
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile  # Ensure this path is correct relative to the root of your repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}