name: CI-CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY_URL: docker.io/sachinparihar
  IMAGE_NAME: go-weather-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          cd src/Backend
          go build -o weather-app ./main.go

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_REGISTRY_URL }}//go-weather-app:${{ github.run_id }} ./src/Backend
          docker push ${{ env.DOCKER_REGISTRY_URL }}//go-weather-app:${{ github.run_id }}
